#Regras de Monitoramento CPU

groups:
  - name: AlertaServidor
    rules: 
     - alert:  AutoCargaDeCPU
       expr: 100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[2m])) * 100) > 1
       for: 1m
       labels:
         severity: warning
       annotations:
         summary: "Uso alto de Cpu (instância{{ $labels.instance }})"
         description:  "O Uso da CPU está em {{$value | printf \".2f\" }}% por mais de 5 minutos."

      #Memoria RAM

     - alert:  ConsumoALtodeMemoria                                                                                                                                         
       expr: (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100 < 90
       for: 1m
       labels:
         severity: critical  
       annotations:
        summary: "Memória RAM baixa (instância{{ $labels.instance }})"
        description:  "Apena {{$value | printf \".2f\" }}% de memória RAM está disponível."

      #Disco
     - alert:  PoucoEspaçoEmDisco
       expr: (node_filesystem_free_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"}) * 100 < 90
       for: 2m
       labels:
        severity: critical  
       annotations:
        summary: "Pouco espaço em disco (instância{{ $labels.instance }})"
        description:  "O disco raiz (/) tem apenas {{$value | printf \".2f\" }}% de espaço livre."